# uncomment lines and config
# AWS_ACCESS_KEY_ID "ACCESS KEY ID HERE"
# AWS_SECRET_ACCESS_KEY "SECRET ACCESS KEY HERE"
# development:
#     AWS_BUCKET: developmentBucket
# production:
#     AWS_BUCKET: productionBucket